# GitHub Actions workflow for destroying Terraform infrastructure
name: Terraform Destroy
on:
  workflow_dispatch: {} # Trigger manually via GitHub Actions UI
jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest # Use Ubuntu runner
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Configure AWS credentials
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # AWS access key from secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS secret key from secrets
          aws-region: us-east-1 # AWS region

      # Set up Terraform
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0 # Specify Terraform version

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Destroy Terraform resources
      - name: Terraform Destroy
        run: terraform destroy -auto-approve